---
platform: linux

inputs:
- name: yq-src

outputs:
- name: postgres-release

run:
  path: postgres-release/ci/tasks/bump-yq-packages/task.sh

params:
  PRIVATE_YML:
  MAJOR_VERSION:
  GIT_USER_NAME: CI Bot
  GIT_USER_EMAIL: bots@cloudfoundry.org
